### ISSUE TITLE
Satis Job fails because of 'Bad Credentials'

### ISSUE THREAD

**Issue by midahp** [maintaina-com/horde-installer-plugin#13]

**Comment by midahp** [comment]
@ralflang It seems like the satis job fails because of credentials: https://github.com/maintaina-com/horde-installer-plugin/runs/7784537156?check_suite_focus=true#step:5:58

Not sure if this is only for this repo a or general problem.

**Comment by ralflang** [comment]
@midahp I have updated the PHPDOC_TOKEN secret to a newer secret. It should be valid until next year. I don't give out secrets without expiration date under my personal user anymore. Can you please update the secret with something issued by the maintaina-com user to make it not expire? It's not urgent. The job should pass now.

**Comment by midahp** [comment]
I updated the PHPDOC_TOKEN token with one created by maintaina-com-svc
