### ISSUE TITLE
how to register apps when doc folder is not there

### ISSUE THREAD

**Issue by boekhorstb1** [maintaina-com/horde-installer-plugin#20]
I guess Im not looking good enough, is there an easy way to register apps now that the docs directory is located somewhere in vendor @ralflang ? Currenlty my setup is a bit broken because of that :)

**Comment by ralflang** [comment]
The installer *should* scan vendor/horde/app/registry.d/ snippets. I will check later if it still uses the old path, which would be a bug.

**Comment by boekhorstb1** [comment]
Thanks! a so files should be in vendor/horde/app/registry.d right? just making sure @ralflang . Is there a way I can see that apps are registered? (trying to figure that out now)

**Comment by ralflang** [comment]
You found a bug. An app can provide its registry snippet from the canonical doc/registry.d dir as before. But this is broken in 2.5.1 - I will roll a 2.5.2 later tonight.

**Comment by boekhorstb1** [comment]
ok thanks @ralflang

**Comment by ralflang** [comment]
I won't be able to test the latest code tonight. Can you manually do

```composer require horde/horde-installer-plugin dev-FRAMEWORK_6_0```

and then, obviously,

```composer horde-reconfigure``

I will release 2.5.2 once I am confident this works as desired.

**Comment by boekhorstb1** [comment]
Ok got following error @ralflang :
````
n HordeReconfigureFlow.php line 31:
                                                                               
  [TypeError]                                                                  
  Argument 1 passed to Horde\Composer\HordeReconfigureFlow::__construct() mus  
  t be an instance of Horde\Composer\DirectoryTree, instance of Horde\Compose  
  r\IOAdapter\ComposerIoAdapter given, called in /srv/www/horde/vendor/horde/  
  horde-installer-plugin/src/HordeInstaller.php on line 28                     
                                                                            
````

**Comment by ralflang** [comment]
This should be an upgrade artifact. When you run this twice, it should not happen. I have tested this in the morning on fresh installs and it did work, both in installer (when require-ing new packages) and in command mode (run through composer horde-reconfigure). I also had this on the first run in an upgrade but not in later runs on that same install. 

Basically, composer still has the old plugin registered but tries to run it with the new code. I will do a release.
