### ISSUE TITLE
horde-reconfigure error

### ISSUE THREAD

**Issue by boekhorstb1** [maintaina-com/horde-installer-plugin#21]
After restarting the first setup and running composer-reconfigure following errors come up in horde-deployment @ralflang :

````
$ composer horde-reconfigure
Applying /presets for absent files in /var/config
Looking for registry snippets from apps
Writing app configs to /var/config dir
Linking app configs to /web Dir

In ConfigLinker.php line 73:
                                        
  symlink(): No such file or directory  

````

**Comment by boekhorstb1** [comment]
will try to find it out

**Comment by boekhorstb1** [comment]
OK I found some solution, see this [MR](https://github.com/maintaina-com/horde-installer-plugin/pull/22) @ralflang 

But now another error is spwaning:

````
In Filesystem.php line 424:
                                                                                                                 
  $from (./web/js/horde/activesyncadmin.js) and $to (./web/horde/js/activesyncadmin.js) must be absolute paths.  
                                                                                                                 
````

**Comment by ralflang** [comment]
It would be helpful if you provided either a unit test or a how to reproduce.

**Comment by boekhorstb1** [comment]
ok, so to reproduce @ralflang :
- setup the deployments containers
- make sure that the latest version of horde-installer is installed (the latest commit of FRAMEWORK_6_0 should show)
- restart the containers and see the logs (or try composer horde-reconfiger)

**Comment by ralflang** [comment]
I could reproduce the issue in the image build pipeline and then fix it. You might want to upgrade installer plugin once again or just fetch the latest image.

**Comment by boekhorstb1** [comment]
thanks a lot, that seems to have done the trick! @ralflang
