### ISSUE TITLE
Problem 'App is not registered'

### ISSUE THREAD

**Issue by boekhorstb1** [maintaina-com/horde-installer-plugin#9]
It seems that the new release does not copy the registry file from doc/registry.d/some-app.php to var/config/registry.d/

**Comment by ralflang** [comment]
@boekhorstb1 Would you please check if the newly released v2.4.1 still has this?

**Comment by ralflang** [comment]
I think I see the issue. One aspect handled by the original installer, creation of registry.d snippets including web and file locations for themes dir, js dir, is missing.

**Comment by boekhorstb1** [comment]
ok will check

**Comment by boekhorstb1** [comment]
ok we have found a small error concerning $appName, see Mahdis PM.

There are still issues, but Im not sure if they are related so I will let you know... For example: I cannot see the permissions in the horde portal, although they are there in the Database, maybe because some js is not loading? Devconsole in firefox shows lots of "Loading failed for the <script> with source ..."

**Comment by ralflang** [comment]
Probably missing/wrong paths for the jsfs and jswebdir (whatever their real key name are, don't have them at hand right now)

**Comment by ralflang** [comment]
Yes, due to a missing <?php tag in an autoconfigured file the jswebdir was not set to the right location. This should be automatically included in tomorrow's image builds.

**Comment by boekhorstb1** [comment]
jap, this is solved :) php-tag did the trick
